default_install_hook_types:
  - pre-commit

repos:
  - repo: local
    hooks:
      - id: prettier-typescript
        name: Prettier TypeScript
        entry: prettier --write --config prettier.config.mjs
        language: system
        files: ^ai/.*\.(?:[cm]?ts|tsx)$
        stages:
          - pre-commit
